version: '3'

services:
  app:
    build: .
    ports:
      - "8080:5000"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db-entrega1-devops-2024.ch66k0eq2upv.us-east-1.rds.amazonaws.com
      FLASK_ENV: development
