version: '3'

services:
  app:
    build: .
    ports:
      - "8080:5000"
    depends_on:
      - db
    volumes:
      - ./app:/app
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://myuser:mypassword@db/mydatabase" 
      FLASK_ENV: development 

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data 
    ports:
      - "8081:5432"

volumes:
  db_data:
