version: "3"

services:
  app:
    build: .
    ports:
      - "8080:5000"
    environment:
      POSTGRES_DB: miso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      POSTGRES_HOST:
      FLASK_ENV: development
